### ISSUE TITLE
spotify js

### ISSUE THREAD

**Issue by mikebutts** [axeltalmet/drummming#1]
https://github.com/axeltalmet/drummming/blob/6c3b94b01f8a9bfe9a93522e3d402b8531c6e853/src/util/Spotify.js#L1-L78

Excellent job on this section, it's rare I don't find something to nit-pick! That being said, did you deploy this? if not you should try to do so.

**Comment by axeltalmet** [comment]
I am just running it locally and it works well. I will deploy after I added some additional features in the next task. Thanks! :)
