### ISSUE TITLE
Alternative

### ISSUE THREAD

**Issue by mikebutts** [axeltalmet/drummming#2]
https://github.com/axeltalmet/drummming/blob/6c3b94b01f8a9bfe9a93522e3d402b8531c6e853/src/Components/App/App.js#L26-L32

just an alternative to this, using find over includes

```
 addTrack(track) {
    let tracks = this.state.playlistTracks;
    if (tracks.find(savedTrack => savedTrack.id === track.id)) {
      return;
    }
```

**Comment by axeltalmet** [comment]
Looks way cleaner. Will keep in mind for the future. Thanks!
