### ISSUE TITLE
Clear the state

### ISSUE THREAD

**Issue by mikebutts** [axeltalmet/drummming#3]
https://github.com/axeltalmet/drummming/blob/6c3b94b01f8a9bfe9a93522e3d402b8531c6e853/src/Components/App/App.js#L44-L47

clear out the playlistname and tracks on save

```
  savePlaylist() {
    const trackUris = this.state.playlistTracks.map(track => track.uri);
    Spotify.savePlaylist(this.state.playlistName, trackUris).then(() => {
      this.setState({
        playlistName: 'New Playlist',
        playlistTracks: []
      });
    });
  }
```

**Comment by axeltalmet** [comment]
Very good point. Actually bugged me when i was testing this out that I was saying multiple identical playlist. Never thought about clearing the state after each save.
