### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by mikebutts** [axeltalmet/drummming#5]
https://github.com/axeltalmet/drummming/blob/6c3b94b01f8a9bfe9a93522e3d402b8531c6e853/src/Components/SearchBar/SearchBar.js#L26-L30

Great way to handle abuse of an api! I have not seen any users add this sort of feature.

**Comment by axeltalmet** [comment]
Thanks, it is actually a twofold implementation. 

1. is to not abuse the api as you mention.
2. To fire a search event after a users stops typing. Instead of having to press enter or the search button. :)
