### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by mikebutts** [axeltalmet/drummming#6]
Exceeds Expectations

Of the tens if not hundreds of these I have reviewed I can only remember 1 or 2 I gave exceeeds expectations. This was very well done and had some extra features on this that I really enjoyed seeing , fantastic job. I would expect a great feature request and you should try implementing this as well as I think you will have no problem with this. Keep up the great work.

**Comment by axeltalmet** [comment]
Thanks for all the motivating feedback, really appreciate it!
